

service: recipes-api

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'recipes-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["RecipesDynamoDBTable", "Arn"] }
  environment:
    RECIPES_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getRecipe:
    handler: index.handler
    events:
      - http: 'GET /recipes/{proxy+}'

  addRecipe:
    handler: index.handler
    events:
      - http: 'POST /recipes'

resources:
    Resources:
      RecipesDynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          TableName: ${self:custom.tableName}
          AttributeDefinitions:
            - AttributeName: recipeShortName
              AttributeType: S
          KeySchema:
            - AttributeName: recipeShortName
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1